# Generated by Django 2.2.4 on 2021-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210331_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='users_added',
            field=models.ManyToManyField(related_name='film', to='first_app.User'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='users_watched',
            field=models.ManyToManyField(related_name='watch', to='first_app.User'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_added', models.ManyToManyField(related_name='film_list', to='first_app.User')),
                ('users_watched', models.ManyToManyField(related_name='watched', to='first_app.User')),
            ],
        ),
    ]
