# Generated by Django 2.2.4 on 2021-03-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210331_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='poster_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
